// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rifzukjgiwpoddagypaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpZnp1a2pnaXdwb2RkYWd5cGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDQ5NDQsImV4cCI6MjA3MjU4MDk0NH0.U3ofQDTZZMldhHnpB4gmZIQapzFTwyAZl_F226dnKOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});